# Generated by Django 6.0.5 on 2026-05-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='days_remaining',
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField(default=100)),
                ('obtained_marks', models.IntegerField()),
                ('grade', models.CharField(choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Above Average'), ('C', 'Average'), ('F', 'Fail')], max_length=5)),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
    ]
